// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// Add provides a mock function with given fields: imageName, imageID
func (_m *Cache) Add(imageName string, imageID string) {
	_m.Called(imageName, imageID)
}

// AddSilent provides a mock function with given fields: imageName, imageID
func (_m *Cache) AddSilent(imageName string, imageID string) {
	_m.Called(imageName, imageID)
}

// OnAdd provides a mock function with given fields: _a0
func (_m *Cache) OnAdd(_a0 func(string, string)) {
	_m.Called(_a0)
}

// OnEvict provides a mock function with given fields: _a0
func (_m *Cache) OnEvict(_a0 func(string, string)) {
	_m.Called(_a0)
}
