// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mover is an autogenerated mock type for the Mover type
type Mover struct {
	mock.Mock
}

// FromDockerToStorage provides a mock function with given fields: ctx, imageName
func (_m *Mover) FromDockerToStorage(ctx context.Context, imageName string) error {
	ret := _m.Called(ctx, imageName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, imageName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FromStorageToDocker provides a mock function with given fields: ctx, imageName
func (_m *Mover) FromStorageToDocker(ctx context.Context, imageName string) error {
	ret := _m.Called(ctx, imageName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, imageName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
